[project]
name = "ocular"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "celery[redis]>=5.6.3",
    "email-validator>=2.3.0",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.139.0",
    "httpx2>=2.5.0",
    "insightface>=1.0.1",
    "numpy>=2.5.1",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.20",
    "regex>=2026.9.10",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.50.0",
]
